#! /bin/sh

while read file
do
    case "$1" in
	"C-s")
#	    nitrogen --set-zoom-fill "$file" ;;
	    #	    sxiv -t /mnt/DATA/juan/Drive/WALLPAPERS/*
	    echo "$file" > ~/.config/bg
	    xwallpaper --zoom $(cat ~/.config/bg)
#	    wal -i "$(cat ~/.config/bg)";;
    esac
done

