#! /bin/sh

while read file
do
    case "$1" in
	"C-w")
	    echo "set \$bg $file" > ~/.config/sway/background
	    swaymsg output \* bg $(cat ~/.config/sway/background | cut -d ' ' -f3) fill
	    notify-send "Fondo de pantalla modificado" ;;
    esac
done

