#!/usr/bin/env bash
hc() {
    herbstclient "$@"
}

hc emit_hook reload
xsetroot -solid '#5A8E3A'
xsetroot -cursor_name left_ptr
sxhkd -c ~/.config/sxhkd/sxhkd_dwm &

# remove all existing keybindings
hc keyunbind --all
Mod=Mod4   
hc set focus_follows_mouse true

hc keybind $Mod-Control-r reload
hc keybind $Mod-Shift-q close_or_remove
hc keybind $Mod-Control-q remove #remove frame, merge client with the next frame

# basic movement in tiling and floating mode
hc keybind $Mod-Control-m spawn ~/.config/herbstluftwm/maximize.sh
hc keybind $Mod-z spawn ~/.config/herbstluftwm/scratch.sh "󱐀"
hc keybind $Mod-Shift-z move "󱐀"

# focusing clients inside the container
hc keybind $Mod-h  focus left
hc keybind $Mod-j  focus down
hc keybind $Mod-k  focus up
hc keybind $Mod-l  focus right

# Focusing containers on the direction
hc keybind $Mod-Mod1-h  focus -e left
hc keybind $Mod-Mod1-j  focus -e down
hc keybind $Mod-Mod1-k  focus -e up
hc keybind $Mod-Mod1-l  focus -e right

# moving clients in tiling and floating mode
hc keybind $Mod-Shift-h shift left
hc keybind $Mod-Shift-j shift down
hc keybind $Mod-Shift-k shift up
hc keybind $Mod-Shift-l shift right

# move client TO OTHER FRAME
hc keybind $Mod-Mod1-Shift-h shift -e left
hc keybind $Mod-Mod1-Shift-j shift -e down
hc keybind $Mod-Mod1-Shift-k shift -e up
hc keybind $Mod-Mod1-Shift-l shift -e right

hc keybind $Mod-Control-j cycle +1
hc keybind $Mod-Control-k cycle -1

# splitting frames
hc keybind $Mod-i  chain , split bottom  0.5 , focus -e down 
hc keybind $Mod-o  chain , split right   0.5 , focus -e right
hc keybind $Mod-Control-i  chain , split top  0.5 , focus -e up
hc keybind $Mod-Control-o  chain , split left   0.5 , focus -e left

# Split but no focus
hc keybind $Mod-Control-v       split   bottom  0.5
hc keybind $Mod-Control-b       split   right   0.5

# Split by half from the longest side
hc keybind $Mod-Control-space split explode

# resizing frames and floating clients
resizestep=0.02
hc keybind $Mod-Mod1-Control-h resize left +$resizestep
hc keybind $Mod-Mod1-Control-l resize right +$resizestep
hc keybind $Mod-Mod1-Control-j resize down +$resizestep
hc keybind $Mod-Mod1-Control-k resize up +$resizestep

hc keybind $Mod-Shift-Control-h resize left -$resizestep
hc keybind $Mod-Shift-Control-l resize right -$resizestep
hc keybind $Mod-Shift-Control-j resize down -$resizestep
hc keybind $Mod-Shift-Control-k resize up -$resizestep

# cycle through tags
hc keybind $Mod-Control-l use_index +1 --skip-visible #next tag
hc keybind $Mod-Control-h use_index -1 --skip-visible #prev tag

# layouting
hc keybind $Mod-F11 fullscreen toggle
hc keybind $Mod-s set_attr clients.focus.floating toggle #float focused client
#hc keybind $Mod-p pseudotile toggle 
hc keybind $Mod-m cycle_layout +1 max vertical #monocle, but inside the frame
hc keybind $Mod-r rotate

hc keybind $Mod-t cycle_layout +1 horizontal vertical #change direction of clients
hc keybind $Mod-g set_layout grid #change direction of clients

hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

hc keybind $Mod-comma   cycle_monitor +1
hc keybind $Mod-period  cycle_monitor -1


# move client to othe MONITOR
hc keybind $Mod-Shift-comma shift_to_monitor +1
hc keybind $Mod-Shift-period shift_to_monitor -1

hc set default_frame_layout horizontal

#tag_names=( 1 2 3 4 5 )
tag_names=( "󰣇" "󰨇" "󰹑" "󱐀" )
#tag_names=( 1 2 3 4 5 6 )
tag_keys=( {1..5} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done


hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1

# Declare some colors

active=8E5EBC
activeAlt=ebdbb2
inactive=22212C
inactiveAlt=6272A4
background=282a36
foreground=ffffff

hc set title_font = DejaVu 10

# Frames
hc set frame_border_active_color "#$active" #Focused frame color
hc set frame_border_normal_color "#$background" #Unfocused frame color
hc set frame_border_width 0  #border size

hc set frame_bg_active_color "#00000000" #Fill of focused frame
hc set frame_bg_normal_color "#00000066" #Fill of unfocused frame (needs always show frame)
hc set frame_bg_transparent off #Removes the filler color of frame
hc set frame_transparent_width 2 # What part of the filler color should remain?

hc set frame_active_opacity 100 #Focused frame opacity
hc set frame_normal_opacity 100 # Unfocused frame opacity

hc set frame_border_inner_width 0
hc set always_show_frame on
hc set frame_gap 5

# Clients
hc attr theme.padding_top 0 #Padding at the top of the windows
hc attr theme.padding_right 0 #Padding 
hc attr theme.padding_left 0 #Padding 
hc attr theme.padding_bottom 0 #Padding 

# WIndow and tabs color/border
hc attr theme.border_width 0 # WIndows border  s
hc attr theme.active.color "#$background" #Window border color
hc attr theme.normal.color "#$inactive" # Window border color unfocused
hc attr theme.urgent.color orange

# Window Title
hc attr theme.title_height 15
hc attr theme.title_depth 5
hc attr theme.title_align center
hc attr theme.title_when multiple_tabs
hc attr theme.floating.title_when always
hc attr theme.padding_top 3

hc attr theme.tiling.title_height 15
hc attr theme.active.color "#$active"
hc attr theme.active.title_color "#$foreground"
hc attr theme.normal.color "#$background"
hc attr theme.normal.title_color "#$foreground"

# TABS
hc attr theme.tab_color "#$inactive"
hc attr theme.tab_title_color "#$inactiveAlt"



# Color for the inner frame.
hc attr theme.inner_width 0
hc attr theme.normal.inner_width 0
hc attr theme.active.inner_color "#ff0000"
hc attr theme.normal.inner_color "#000000"

# Color for the outer frame (This is seen with tabs)
hc attr theme.outer_width 0
hc attr theme.active.outer_color "#$activeAlt"
hc attr theme.normal.outer_color "#$inactive"

# Colors for floating 

hc attr theme.floating.title_height 15
hc attr theme.floating.title_depth 3
hc attr theme.floating.outer_width 0
hc attr theme.floating.normal.outer_color "#$background"
hc attr theme.floating.active.outer_color "#$background"
hc attr theme.floating.border.width 0
hc attr theme.background_color "#$background"

hc attr theme.floating.active.color "#$active"
hc attr theme.floating.normal.color "#$inactive"
hc attr theme.floating.normal.title_color "#$inactive"
hc attr theme.floating.active.title_color "#$foreground"

# Color for the inner frame
hc attr theme.floating.inner_width 0
hc attr theme.floating.active.inner_color "#$color1"
hc attr theme.floating.normal.inner_color "#$color5"

hc set window_gap 0 #Gap between windows
hc set frame_padding 0 # Gapp between windows and frames
hc set smart_window_surroundings off
hc set smart_frame_surroundings off
hc set mouse_recenter_gap 0
hc set hide_covered_windows off

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
hc rule floatplacement=center
hc rule class=Pqiv floating=on
hc rule class=Ulauncher floating=on focus=on
hc rule class=conky floating=on
hc rule class=Steam floating=on
hc rule class=mpv floating=on
hc rule class=Lxappareance floating=on
hc rule class=Pavucontrol floating=on
hc rule class=qt5ct floating=on
hc rule class=Sxiv floating=on
hc rule class=kruler floating=on
hc rule class=zoom floating=on
hc rule class=Connman-gtk floating=on
hc rule instance=calendar.txt floating=on
hc rule class=Emacs title=capture floating=on 

##### ZOOM
hc rule class=zoom title~"Chat.*" tag=󰨇 floating=off index=1
hc rule class=zoom title~"Participants.*" tag=󰨇 floating=off index=1
hc rule class=zoom title="Zoom Meeting" tag=󰨇 floating=off index=0
hc rule class=zoom title="Zoom" tag=󰨇 floating=off index=0
hc rule class=zoom title="Zoom - Free Account" tag=󱐀 floating=off
hc rule class=zoom title="Zoom Cloud Meetings" tag=󱐀 floating=off



hc rule windowtype~'_NET_WM_WINDOW_TYPE_DESKTOP' manage=off
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on


hc set tree_style '╾│ ├└╼─┐'
# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:

# Restart picom if needed
autorandr --change
hc detect_monitors

killall picom ; picom &
nitrogen --restore &
# find the panel and restart it if needed
killall polybar ; polybar -r panel &
