# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "sr_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/dba8abe1-5829-4810-bbc2-ff0de5dfdb85";
      fsType = "ext4";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/e9701771-e11c-44ef-9eb0-85605cfe5178";
      fsType = "ext4";
    };

  fileSystems."/mnt/data" =
    { device = "/dev/disk/by-uuid/2ca94392-9695-4a84-a552-c97617791b01";
      options = [ "rw" "users" ];
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/7b8f08d7-f2d2-44f8-b7c7-d341d8133a2b"; }
    ];

}
