#! /bin/bash

bspc subscribe node_add node_remove | 
    while read -r line; do
	var=$(echo $line | awk '{print $1}')
	echo $var
	if [ "$var" == "node_add" ]; then
	    #	bspc node biggest.tiled.local -E
	    bspc node biggest.tiled.local#@brother -B
#	    bspc node -s biggest.local
	elif [ "$var" == "node_remove" ]; then
	    bspc node @/ -E
	    bspc node biggest.tiled.local#@brother -B
#	    bspc node -s biggest.local
	fi
    done;

