#! /bin/sh

sxhkd -c ~/.config/sxhkd/sxhkdrc &
~/.config/polybar/polybar-monitors.sh &

#. "${HOME}/.cache/wal/colors.sh"
#. "${HOME}/.Xresources"

bspc config automatic_scheme spiral
bspc config initial_polarity first_child

bspc monitor LVDS-1 -d I II III IV
bspc monitor VGA-1 -d V VI VII
bspc monitor HDMI-1 -d A S D
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc config border_width        2
bspc config window_gap           10
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#1d2021"
bspc config active_border_color "#1d2021"
bspc config focused_border_color "#98971a"
bspc config presel_feedback_color "#98971a"

#bspc config normal_border_color   "$color0"
#bspc config active_border_color   "$color0"
#bspc config focused_border_color  "$color2"
#bspc config presel_feedback_color "$color2"

##############
#REGLAS
##############

bspc rule -a Gimp desktop='^3' follow=on
bspc rule -a Screenkey manage=off
bspc rule -a Rofi manage=off
#bspc rule -a Firefox desktop='^2' follow=on
#bspc rule -a Firefox-esr desktop='^2' follow=on
bspc rule -a Chromium desktop='^2' follow=on
bspc rule -a Spotify desktop='^4' follow=off
bspc rule -a Lxappareance state=floating
bspc rule -a Lightdm-settings state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a qt5ct state=floating
bspc rule -a virtualbox state=floating
bspc rule -a Gucharmap state=floating
bspc rule -a Emacs state=tiled
bspc rule -a Oblogout state=fullscreen
bspc rule -a Zathura state=tiled
bspc rule -a MPlayer state=floating
bspc rule -a Sxiv state=floating
bspc rule -a mpv state=floating
bspc rule -a Qalculate-gtk state=floating
bspc rule -a '*:libreofficedev' state=tiled
bspc rule -a 'libreoffice' state=tiled
bspc rule -a '*:soffice' state=tiled
bspc rule -a Emacs:capture state=floating
bspc rule -a Emacs:mu4e state=floating
bspc rule -a Emacs:agenda state=floating
bspc rule -a Emacs:todotxt state=floating
bspc rule -a Steam state=floating

bspc config external_rules_command ~/.config/bspwm/external_rules.sh
