#! /bin/sh

#   ██                                            
#  ░██              ██████                        
#  ░██       ██████░██░░░██ ███     ██ ██████████ 
#  ░██████  ██░░░░ ░██  ░██░░██  █ ░██░░██░░██░░██
#  ░██░░░██░░█████ ░██████  ░██ ███░██ ░██ ░██ ░██
#  ░██  ░██ ░░░░░██░██░░░   ░████░████ ░██ ░██ ░██
#  ░██████  ██████ ░██      ███░ ░░░██ ███ ░██ ░██
#  ░░░░░   ░░░░░░  ░░      ░░░    ░░░ ░░░  ░░  ░░
#

sxhkd &
#wal -R &
nitrogen --restore &
#~/.config/polybar/polybar_launch.sh &
~/.config/polybar/polybar-monitors.sh &
# ~/.config/bspwm/conky-restart &

##################
#BSPWM CONFIG
##################

. "${HOME}/.cache/wal/colors.sh"

bspc config automatic_scheme spiral
bspc config initial_polarity first_child

bspc monitor LVDS-1 -d 1 2 3 4 5 6
bspc monitor VGA-1 -d 7 8 9
bspc monitor HDMI-1 -d A S D
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc config border_width        3
bspc config window_gap           10
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc config normal_border_color "#151b22"
#bspc config active_border_color "#151b22"
#bspc config focused_border_color "#3d587a"
#bspc config presel_feedback_color "#3d587a"

bspc config normal_border_color "$color1"
bspc config active_border_color "$color1"
bspc config focused_border_color "#ca2026"
bspc config presel_feedback_color "#ca2026"

##############
#REGLAS
##############

bspc rule -a Gimp desktop='^5' follow=on
bspc rule -a Screenkey manage=off
bspc rule -a Rofi manage=off
bspc rule -a firefox desktop='^2' follow=on
bspc rule -a Firefox-esr desktop='^2' follow=on
bspc rule -a Chromium desktop='^2' follow=on
bspc rule -a Spotify desktop='^6'
bspc rule -a Lxappareance state=floating
bspc rule -a Lightdm-settings state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a qt5ct state=floating
bspc rule -a virtualbox state=floating
bspc rule -a Gucharmap state=floating
bspc rule -a Emacs state=tiled
bspc rule -a Oblogout state=fullscreen
bspc rule -a Zathura state=tiled
bspc rule -a MPlayer state=floating
#bspc rule -a Sxiv state=floating
bspc rule -a mpv state=floating
bspc rule -a Qalculate-gtk state=floating
bspc rule -a '*:libreofficedev' state=tiled
bspc rule -a 'libreoffice' state=tiled
bspc rule -a '*:soffice' state=tiled
bspc rule -a Emacs:capture state=floating
bspc rule -a Emacs:mu4e state=floating
bspc rule -a Emacs:agenda state=floating
bspc rule -a Emacs:todotxt state=floating
bspc rule -a Steam state=floating
bspc rule -a 'st-256color:guy' state=floating
bspc rule -a '*:cmus' state=floating

bspc config external_rules_command ~/.config/bspwm/external_rules.sh
#############
#AUTOSTART
#############

# Crea un archivo de bloqueo en /tmp al arrancar y ejecuta todo, en siguientes ejecuciones de bspwmrc, el archivo existirá, y por lo tanto, no se ejecutará nada, evitando instancias repetidas

#startup_lock_file=/tmp/bspwm-startup.lock
#if [ ! -f $startup_lock_file ]; then
#    echo "dummy" > $startup_lock_file
#   
## Agregar las aplicaciones de autoarranque debajo de esta línea
##==========================================================================================================================
#compton -b --config ~/.config/compton.conf &
#xfce4-power-manager &
#pcloud &
#copyq &
#conky -c ~/conkys/reloj-texto &
#emacs --daemon &
#~/.config/polybar/polybar-monitors.sh &
#/usr/lib/kdeconnectd &
#redshift &
#xsetroot -cursor_name left_ptr &
##~/.config/bspwm/auto-balance-stack
##conky -c ~/conkys/material &
##conky -c ~/conkys/agenda &
## xautolock -locker i3lock-fancy -f Fantasque-Sans-Mono-Regular -t Contraseña, mode "default" &
## polybar -c ~/.config/polybar/config example -r &
##pacmd load-module module-remap-sink sink_name=mono master=alsa_output.pci-0000_00_14.2.analog-stereo channels=2 channel_map=mono,mono &
##xrdb -load ~/.Xresources &
##numlockx on &
#
##==========================================================================================================================
#fi
