#! /bin/sh


if [ -e /tmp/BSPWM-SPIRAL-LOCK ]; then
    rm /tmp/BSPWM-SPIRAL-LOCK
    notify-send -a "bspwm" "Esquema master & stack"
else
    touch /tmp/BSPWM-SPIRAL-LOCK
    notify-send -a "bspwm" "Esquema spiral"
fi
