#!/bin/sh

#var=$(echo -e " Apagar\n Bloquear\n Suspender\n Reiniciar\n Cerrar sesión\n Cancelar" | rofi -dmenu -theme drofi -i -p "¿Desea salir?") 
var=$(echo " Apagar\n Reiniciar\n Salir\n Bloquear\n Suspender\n  Cancelar" | dmenu -i -p "¿Desea salir?") 

case $var in
    ' Apagar') 
#       rm /tmp/bspwm-startup.lock
#	systemctl poweroff;;
	poweroff;;
	

    ' Bloquear')
	i3lock -f -i /home/juan/.cache/i3lock/1633x768/blur.png;;

    ' Reiniciar')
#	rm /tmp/bspwm-startup.lock
#	systemctl reboot;;
	reboot;;

    ' Salir')
#	rm /tmp/bspwm-startup.lock
#	bspc quit;;
	pkill xinit;;
    ' Suspender')
#	systemctl suspend;;
	sudo zzz;;
    
	' Cancelar')
	    exit 0;;
esac
