#!/bin/sh

#var=$(echo -e " Apagar\n Bloquear\n Reiniciar\n Cerrar sesión\n Cancelar" | rofi -dmenu -theme drofi -i -p "¿Desea salir?") 
var=$(echo " Apagar\n Bloquear\n Reiniciar\n Cerrar sesión\n Cancelar" | dmenu -i -p "¿Desea salir?") 

case $var in
    ' Apagar') 
	rm /tmp/bspwm-startup.lock
	systemctl poweroff;;
	

    ' Bloquear')
	i3lock -f -i /home/juan/Pictures/lock.png;;

    ' Reiniciar')
	rm /tmp/bspwm-startup.lock
	systemctl reboot;;

    ' Cerrar sesión')
		rm /tmp/bspwm-startup.lock
		bspc quit;;
	' Cancelar')
	    exit 0
esac
