#! /bin/sh

fecha(){
    date '+%b %d, %H:%M'
}

bat(){
    echo "$(cat /sys/class/power_supply/BAT0/capacity)%"
    }

vol(){
    echo "$(amixer get Master | awk -F'[][]' 'END{ print $2 }')"
    }

red(){
    if ping gnu.org -c1 > /dev/null; then
	echo ""
    else
	echo "--"
    fi
   } 

#kbd(){
#    key=$(xmodmap -pke | grep -w "59" | awk '{print $5}')
#    echo $key
#    case $key in
#	less)
#	    echo "us";;
#	semicolon)
#	    echo "mex";;
#	esac
#    }

while true; do

    out=$(echo "$(fecha) | Bat: $(bat) | $(red)")
#    echo $out | tr '\n' ' '

    xsetroot -name "$out"
    echo "$out"
    
    sleep 1m
done
