#!/bin/sh

fortune amistad arte asimov ciencia deprimente familia famosos filosofia humanos informatica jojos leydemurphy libertad linux nietzsche pintadas poder proverbios refranes sabiduria schopenhauer sentimientos varios varios-pre verdad vida eva
