#! /bin/sh

sel=$(echo "Derecha\nIzquierda\nArriba\nAbajo\nEspejo" | dmenu -i -p "¿Dónde desea ubicar el monitor conectado?")
    
echo $sel
case $sel in
    Espejo) mons -d && killall compton && compton -b --config ~/.config/compton.conf;;
    Derecha) mons -e right killall compton && compton -b --config ~/.config/compton.conf;;
    Izquierda) mons -e left killall compton && compton -b --config ~/.config/compton.conf;;
    Arriba) mons -e top killall compton && compton -b --config ~/.config/compton.conf;;
    Abajo) mons -e bottom killall compton && compton -b --config ~/.config/compton.conf;;
esac
