#! /bin/sh

sel=$(echo "Derecha\nIzquierda\nArriba\nAbajo\nEspejo" | dmenu -i -p "¿Dónde desea ubicar el monitor conectado?")
    
echo $sel
case $sel in
    Espejo) mons -d;;
    Derecha) mons -e right;;
    Izquierda) mons -e left;;
    Arriba) mons -e top;;
    Abajo) mons -e bottom;;
esac
