#! /bin/sh

sel=$(pacman -Ssq | dmenu -l 20 -p "Pacman") #seleccionar un paquete del repo
if [ "$sel" == "" ]; then
    exit 0 #si se presiona ESC, el script termina
else
    pass=$(dmenu -P -p "Contraseña") #Pedir conraseña usando dmenu
    a=$(echo $pass | sudo -Skv) #Revisar si la contraseña ingresada es correcta
    if [ $? == 0 ]; then
	#Si la contraseña es correcta, ejecuta pacman para instalar el programa deseado en una ventana de st flotante
	bspc rule -a \* -o state=floating && st -e sh -c "echo "$pass" | sudo -S pacman -S "$sel" --noconfirm; read -p 'Presione enter para salir'"
    else
	notify-send -a "Pacman" "Contraseña incorrecta" #si la contraseña es incorrecta, manda una notificación
    fi
fi
