#! /bin/sh
 echo "ﮨ"

bspc subscribe desktop_layout |
    while read -r line; do
	var="$(echo "$line" |  awk '{print $4}')" 
	case "$var" in
	    tiled) if [ -e /tmp/BSPWM-SPIRAL-LOCK ]; then
		       echo ""
		   else
		       echo "ﮨ"
		   fi;;
	    
	    monocle) echo "﨣";;
	esac
    done
